[BACKLOG-35528] convert log4j.xml to log4j2.xml with file rename
pentaho/pentaho-reporting pull request #1469
Opened 2022-01-26 15:03 UTC by ddiroma

2022-01-26 15:10 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/prd-ce
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-01-26 22:25 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/prd-ce
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-01-27 14:38 UTC, buildguy commented
### :white_check_mark: Build finished in 4m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/prd-ce
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-01-27 18:50 UTC, buildguy commented
### :white_check_mark: Build finished in 5m 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/prd-ce
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-01-27 19:14 UTC, bennychow requested changes

2022-01-27 19:14 UTC, bennychow commented on assemblies/prd-ce/src/main/resources/resource/system/osgi/log4j2.xml
> +      <Console name="PENTAHOCONSOLE">
Missing Threshold filter set to INFO.  Isn't it weird that we see this set to different levels in different log4j.xml files =)

2022-01-27 19:38 UTC, buildguy commented
### :white_check_mark: Build finished in 3m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/prd-ce
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-01-27 19:43 UTC, bennychow approved these changes

2022-01-27 19:43 UTC, merged