[PPP-4867] Moved emtpy script langauge check and null script context …
pentaho/pentaho-reporting pull request #1569
Opened 2023-05-25 13:37 UTC by MarcDiamantHitachi

…check to happen before allow script eval check

2023-05-26 09:19 UTC, smmribeiro commented
@MarcDiamantHitachi there are some problems with this PR:

- The commit message should state the SP issue. Normally, we use as "[SP-6340] Backport of PPP-4867 - org.pentaho.reporting.engine.classic.core.allowScriptEvaluation error shown when report DOES NOT use scriptable data sources (9.3 Suite)"
- The final code to merge is not completely consistent to the actual code: one can see that there's extra lines on the copyright header immediately and GitHub calculates this PR as "+16 -5" while the original one (#1556) is "+7 -8"... 
- There are two commits on this PR: the "cherry pick" and a merge operation; it seems that the merge operation is "breaking" something?

Could you, please, fix these issues?

2023-05-26 09:21 UTC, smmribeiro requested changes

2023-05-26 09:21 UTC, smmribeiro commented on engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/DataFactoryScriptingSupport.java
> +
Extra lines included...

2023-05-26 09:21 UTC, smmribeiro commented on engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/DataFactoryScriptingSupport.java
> +    }
I think the merge operation is breaking something here and GitHub can't correctly calculate what to merge.

2023-05-26 09:24 UTC, smmribeiro commented
@MarcDiamantHitachi there are some problems with this PR:

The commit message should state the SP issue. Normally, we'd use "**[SP-6340] Backport of PPP-4867 - org.pentaho.reporting.engine.classic.core.allowScriptEvaluation error shown when report DOES NOT use scriptable data sources (9.3 Suite)**"

The final code to merge is not completely consistent to the original code: one can see that there's extra lines on the copyright header immediately and GitHub calculates this PR as "+16 -5" while the original one (https://github.com/pentaho/pentaho-reporting/pull/1556) is "+7 -8"...

There are two commits on this PR: the "cherry pick" and a merge operation; I suspect that the merge operation is "breaking" something.

Could you, please, fix these issues?

2023-05-31 08:40 UTC, andreramos89 approved these changes

2023-05-31 08:46 UTC, smmribeiro approved these changes

2023-05-31 08:46 UTC, merged