[PPP-4899] Vulnerable Component: commons-io
pentaho/pentaho-reporting pull request #1678
Opened 2024-08-12 14:45 UTC by singletonc

Jira: https://hv-eng.atlassian.net/browse/PPP-4899

- Update xmlgraphics-commons 2.2 -> 2.9 -- this gets us to commons-io 2.16.1, which is 2.7+, addressing CVE-2021-29425

```
[INFO] org.pentaho.reporting.library:libloader:jar:10.3.0.0-SNAPSHOT
...
[INFO] +- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.6:compile
[INFO] |  \- commons-io:commons-io:jar:2.16.1:compile
```

2024-08-12 15:03 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-08-12 15:08 UTC, buildguy commented
### :warning: Build finished in 22m 44s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.reporting.engine.classic.core.RotationTest.testHandleRotatedTextHTML</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **1829**, Failures: **1**, Skipped: **17** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting/job/PR-1678/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-08-12 16:07 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-08-12 16:12 UTC, buildguy commented
### :warning: Build finished in 21m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.reporting.engine.classic.core.RotationTest.testHandleRotatedTextHTML</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **1829**, Failures: **1**, Skipped: **17** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/reporting/job/PR-1678/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-08-12 17:48 UTC, singletonc commented
The associated test failure is [failing in the latest 10.3 QAT #41](https://thanos.orl.eng.hitachivantara.com/job/10.3/job/suite-release/41/) it is not failing due to these changes.

2024-08-13 13:35 UTC, NJtwentyone approved these changes

2024-08-13 21:01 UTC, NJtwentyone requested changes
please identify QA tests per - https://hv-eng.atlassian.net/wiki/spaces/ENG/pages/31277645984/Recommended+process+when+reviewing+and+addressing+security+vulnerabilities

and please link or add comment to original jira issue

2024-08-20 21:11 UTC, singletonc commented
> please identify QA tests per - https://hv-eng.atlassian.net/wiki/spaces/ENG/pages/31277645984/Recommended+process+when+reviewing+and+addressing+security+vulnerabilities
> 
> and please link or add comment to original jira issue

This is covered in this PRD test https://eu1-prod.practitest.app/p/13675/tests/2284000

2024-08-30 19:25 UTC, rmansoor approved these changes

2024-08-30 19:25 UTC, merged